export const ITEM__CREATE = 'ITEM__CREATE';
export const FLASH_MESSAGE__CREATE = 'FLASH_MESSAGE__CREATE';
export const FLASH_MESSAGE__DELETE = 'FLASH_MESSAGE__DELETE';
export const POSTS__GET = 'POSTS__GET';
